name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildh:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build package
        run: yarn build
